<?php 
return array (
  'site_name' => '微商企-为每一个品牌微信插上梦想的翅膀!',
  'site_title' => '北京24SO科技有限公司',
  'site_logo' => '/tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://v.24so.com',
  'site_my' => '微商企',
  'server_key' => 'bc9ed510a91c14331cf2f6ce4169807b',
  'server_topdomain' => 'v.24so.co',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_needmp' => 'false',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'router_key' => 'RLGyjbhn',
  'ipc' => '',
  'site_qq' => '79888170',
  'site_mp' => '',
  'baidu_map_api' => '2b79c282b0f365ca9782cceb499e6022',
  'site_email' => '79888170@qq.com',
  'keyword' => '24SO,24搜,二十四搜,北京24搜,北京24so,易信二次开发 微信,易信接口开发 微信,易信托管服务 微信,易信营销 微信,易信公众平台接口开发',
  'content' => '24so意寓全天搜索,全城购物! 微生活,找24so; 想购物,找24so; 24so移动互联最大的商企平台，分公司遍布全国30个以上省市自治区。微信公众平台接口开发、托管、营销活动、二次开发。',
  'countsz' => '',
  'copyright' => '北京24SO微商企版权所有',
);